import 'package:flutter/material.dart';
import 'package:table_calendar/table_calendar.dart';
import 'package:intl/intl.dart';
import '../../../models/production_schedule_model.dart';
import '../../../models/menu_model.dart';
import '../services/schedule_service.dart';
import '../services/menu_service.dart';
import 'package:collection/collection.dart';

// Model sementara untuk hasil kalkulasi yang akan ditampilkan di dialog
class CalculatedProductionItem {
  final String menuName;
  final int portions;
  final int maxConsume;
  final String earliestDeadline; // Format HH:mm
  final int cookingDuration;

  CalculatedProductionItem({
    required this.menuName,
    required this.portions,
    required this.maxConsume,
    required this.earliestDeadline,
    required this.cookingDuration,
  });
}

class ProductionCalendarScreen extends StatefulWidget {
  const ProductionCalendarScreen({super.key});

  @override
  State<ProductionCalendarScreen> createState() =>
      _ProductionCalendarScreenState();
}

class _ProductionCalendarScreenState extends State<ProductionCalendarScreen> {
  final ScheduleService _scheduleService = ScheduleService();
  final MenuService _menuService = MenuService();

  DateTime _focusedDay = DateTime.now();
  DateTime? _selectedDay;

  Map<DateTime, List<ProductionSchedule>> _schedules = {};
  List<Menu> _availableMenus = [];
  bool _isLoading = true;

  @override
  void initState() {
    super.initState();
    _selectedDay = _focusedDay;
    _loadInitialData();
  }

  Future<void> _loadInitialData() async {
    try {
      final menus = await _menuService.getMyMenus();
      _availableMenus = menus;
      _fetchSchedules();
    } catch (e) {
      setState(() => _isLoading = false);
    }
  }

  Future<void> _fetchSchedules() async {
    setState(() => _isLoading = true);
    try {
      // THIS NOW CALLS THE CORRECTLY DEFINED METHOD
      final data = await _scheduleService.getSchedulesByMonth(_focusedDay);

      Map<DateTime, List<ProductionSchedule>> newMap = {};
      for (var item in data) {
        final dateKey = DateTime(
          item.date.year,
          item.date.month,
          item.date.day,
        );
        if (newMap[dateKey] == null) newMap[dateKey] = [];
        newMap[dateKey]!.add(item);
      }
      if (mounted) {
        setState(() {
          _schedules = newMap;
          _isLoading = false;
        });
      }
    } catch (e) {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  List<ProductionSchedule> _getSchedulesForDay(DateTime day) {
    final dateKey = DateTime(day.year, day.month, day.day);
    return _schedules[dateKey] ?? [];
  }

  void _showAutoGenerateDialog() {
    bool isGenerating = false;
    List<MenuProductionDetail> calculatedList = [];

    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (ctx) => StatefulBuilder(
        builder: (context, setDialogState) {
          Future<void> runCalculation() async {
            setDialogState(() => isGenerating = true);
            try {
              final result = await _scheduleService.calculateProductionSchedule(
                _selectedDay!,
              );
              setDialogState(() {
                calculatedList = result;
                isGenerating = false;
              });
            } catch (e) {
              if (mounted) {
                ScaffoldMessenger.of(context).showSnackBar(
                  SnackBar(
                    content: Text("Gagal kalkulasi: $e"),
                    backgroundColor: Colors.red,
                  ),
                );
              }
              setDialogState(() => isGenerating = false);
            }
          }

          // Trigger calculation on first open
          if (calculatedList.isEmpty && !isGenerating) {
            runCalculation();
          }

          // Logic Simpan Jadwal ke DB
          Future<void> saveSchedule() async {
            setDialogState(() => isGenerating = true);
            try {
              await _scheduleService.saveCalculatedSchedule(
                calculatedList,
                _selectedDay!,
              );
              if (mounted) {
                ScaffoldMessenger.of(context).showSnackBar(
                  const SnackBar(
                    content: Text("Jadwal Produksi Tersimpan!"),
                    backgroundColor: Colors.green,
                  ),
                );
                Navigator.pop(ctx);
                _fetchSchedules(); // Refresh Calendar
              }
            } catch (e) {
              if (mounted) {
                ScaffoldMessenger.of(context).showSnackBar(
                  SnackBar(
                    content: Text("Gagal simpan jadwal: $e"),
                    backgroundColor: Colors.red,
                  ),
                );
              }
              setDialogState(() => isGenerating = false);
            }
          }

          return AlertDialog(
            title: Text(
              "Kalkulasi Jadwal ${_selectedDay != null ? DateFormat('d MMM').format(_selectedDay!) : ''}",
            ),
            content: SizedBox(
              width: MediaQuery.of(context).size.width * 0.8,
              child: isGenerating
                  ? const Center(
                      child: Column(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          CircularProgressIndicator(),
                          SizedBox(height: 10),
                          Text("Menganalisis Rute & Deadline..."),
                        ],
                      ),
                    )
                  : calculatedList.isEmpty
                  ? const Center(
                      child: Text("Tidak ada kebutuhan produksi hari ini."),
                    )
                  : SingleChildScrollView(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          const Text(
                            "Urutan Masak (Prioritas Max Consume):",
                            style: TextStyle(fontWeight: FontWeight.bold),
                          ),
                          const SizedBox(height: 10),
                          // Display order in reverse (paling bawah di list ini dimasak duluan, paling atas dimasak paling akhir)
                          ...calculatedList.reversed.toList().mapIndexed((
                            index,
                            item,
                          ) {
                            // <--- FIX: .toList().mapIndexed
                            return Card(
                              color: Colors.blue[50],
                              margin: const EdgeInsets.symmetric(vertical: 4),
                              child: ListTile(
                                leading: Text(
                                  "#${index + 1}",
                                  style: const TextStyle(
                                    fontWeight: FontWeight.bold,
                                    fontSize: 16,
                                  ),
                                ),
                                title: Text(
                                  item.menuName,
                                  style: const TextStyle(
                                    fontWeight: FontWeight.bold,
                                  ),
                                ),
                                subtitle: Text(
                                  "Porsi: ${item.totalPortions} | Masak: ${item.cookingDurationMinutes} mnt\nBatas Konsumsi: ${item.maxConsumeMinutes} mnt",
                                ),
                              ),
                            );
                          }).toList(),
                          const SizedBox(height: 20),
                          const Text(
                            "PERHATIAN: Jadwal yang disimpan akan diurutkan secara BACKWARD SCHEDULING.",
                            style: TextStyle(color: Colors.red, fontSize: 12),
                          ),
                        ],
                      ),
                    ),
            ),
            actions: [
              TextButton(
                onPressed: () => Navigator.pop(ctx),
                child: const Text("Tutup"),
              ),
              if (calculatedList.isNotEmpty && !isGenerating)
                ElevatedButton(
                  onPressed: saveSchedule,
                  child: const Text("SIMPAN JADWAL OTOMATIS"),
                ),
            ],
          );
        },
      ),
    );
  }

  // --- DIALOG CRUD (TAMBAH KHUSUS / EDIT) ---
  void _showScheduleDialog({ProductionSchedule? scheduleToEdit}) {
    String? selectedMenuId = scheduleToEdit?.menuId;
    final portionController = TextEditingController(
      text: scheduleToEdit?.totalPortions.toString() ?? "100",
    );
    final noteController = TextEditingController(
      text: scheduleToEdit?.notes ?? "Tambahan Khusus",
    );

    TimeOfDay selectedTime = const TimeOfDay(hour: 11, minute: 0);
    if (scheduleToEdit?.targetFinishTime != null) {
      final parts = scheduleToEdit!.targetFinishTime!.split(':');
      selectedTime = TimeOfDay(
        hour: int.parse(parts[0]),
        minute: int.parse(parts[1]),
      );
    }

    showDialog(
      context: context,
      builder: (ctx) => StatefulBuilder(
        builder: (context, setDialogState) {
          final currentMenu = _availableMenus.isNotEmpty
              ? _availableMenus.firstWhere(
                  (m) => m.id == selectedMenuId,
                  orElse: () => _availableMenus.first,
                )
              : null;

          String startTimeString = "--:--";
          if (currentMenu != null) {
            startTimeString = _scheduleService
                .calculateStartTime(
                  selectedTime,
                  selectedMenuId != null
                      ? currentMenu.cookingDurationMinutes
                      : 0,
                )
                .substring(0, 5);
          }

          return AlertDialog(
            title: Text(
              scheduleToEdit == null ? "Jadwal Produksi" : "Edit Jadwal",
            ),
            content: SingleChildScrollView(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  if (scheduleToEdit == null)
                    const Text(
                      "Gunakan ini HANYA untuk pesanan tambahan di luar rute rutin.",
                      style: TextStyle(fontSize: 12, color: Colors.red),
                    ),
                  const SizedBox(height: 10),

                  DropdownButtonFormField<String>(
                    decoration: const InputDecoration(
                      labelText: "Pilih Menu",
                      border: OutlineInputBorder(),
                    ),
                    value: selectedMenuId,
                    items: _availableMenus
                        .map(
                          (m) => DropdownMenuItem(
                            value: m.id,
                            child: Text(m.name),
                          ),
                        )
                        .toList(),
                    onChanged: (val) =>
                        setDialogState(() => selectedMenuId = val),
                  ),
                  const SizedBox(height: 10),

                  TextField(
                    controller: portionController,
                    keyboardType: TextInputType.number,
                    decoration: const InputDecoration(
                      labelText: "Jumlah Porsi",
                      border: OutlineInputBorder(),
                    ),
                  ),
                  const SizedBox(height: 10),

                  ListTile(
                    title: const Text("Target Selesai Jam:"),
                    subtitle: Text(
                      selectedTime.format(context),
                      style: const TextStyle(fontWeight: FontWeight.bold),
                    ),
                    trailing: const Icon(Icons.access_time),
                    onTap: () async {
                      final t = await showTimePicker(
                        context: context,
                        initialTime: selectedTime,
                      );
                      if (t != null) setDialogState(() => selectedTime = t);
                    },
                  ),

                  if (selectedMenuId != null && currentMenu != null)
                    Padding(
                      padding: const EdgeInsets.only(top: 10),
                      child: Container(
                        padding: const EdgeInsets.all(8),
                        color: Colors.blue[50],
                        child: Text(
                          "MULAI MASAK: $startTimeString (Durasi: ${currentMenu.cookingDurationMinutes} mnt)",
                          style: const TextStyle(
                            color: Colors.blue,
                            fontWeight: FontWeight.bold,
                            fontSize: 12,
                          ),
                        ),
                      ),
                    ),

                  const SizedBox(height: 10),
                  TextField(
                    controller: noteController,
                    decoration: const InputDecoration(
                      labelText: "Catatan",
                      border: OutlineInputBorder(),
                    ),
                  ),
                ],
              ),
            ),
            actions: [
              TextButton(
                onPressed: () => Navigator.pop(ctx),
                child: const Text("Batal"),
              ),
              ElevatedButton(
                onPressed: () async {
                  if (selectedMenuId == null) return;
                  Navigator.pop(ctx);
                  final menu = _availableMenus.firstWhere(
                    (m) => m.id == selectedMenuId,
                  );

                  if (scheduleToEdit == null) {
                    // TAMBAH KHUSUS
                    await _scheduleService.addSchedule(
                      date: _selectedDay!,
                      menuId: selectedMenuId!,
                      portions: int.parse(portionController.text),
                      deliverTime: selectedTime,
                      cookingDuration: menu.cookingDurationMinutes,
                      notes: noteController.text,
                    );
                  } else {
                    // EDIT JADWAL (Rutin/Khusus)
                    await _scheduleService.updateSchedule(
                      id: scheduleToEdit.id,
                      menuId: selectedMenuId!,
                      portions: int.parse(portionController.text),
                      deliverTime: selectedTime,
                      cookingDuration: menu.cookingDurationMinutes,
                      notes: noteController.text,
                    );
                  }
                  _fetchSchedules();
                },
                child: const Text("Simpan"),
              ),
            ],
          );
        },
      ),
    );
  }

  void _confirmDelete(String id) {
    showDialog(
      context: context,
      builder: (ctx) => AlertDialog(
        title: const Text("Hapus Jadwal?"),
        content: const Text("Jadwal produksi ini akan dihapus."),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx),
            child: const Text("Batal"),
          ),
          TextButton(
            onPressed: () async {
              Navigator.pop(ctx);
              await _scheduleService.deleteSchedule(id);
              _fetchSchedules();
            },
            child: const Text("Hapus", style: TextStyle(color: Colors.red)),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Kalender Produksi"),
        backgroundColor: Colors.orange[800],
        foregroundColor: Colors.white,
      ),
      // [FIX UTAMA]: Bungkus Column utama dengan SingleChildScrollView
      body: SingleChildScrollView(
        child: Column(
          children: [
            // --- KALENDER (Tetap) ---
            TableCalendar<ProductionSchedule>(
              firstDay: DateTime.utc(2024, 1, 1),
              lastDay: DateTime.utc(2030, 12, 31),
              focusedDay: _focusedDay,
              selectedDayPredicate: (day) => isSameDay(_selectedDay, day),
              calendarFormat: CalendarFormat.month,
              eventLoader: _getSchedulesForDay,
              onDaySelected: (selected, focused) {
                setState(() {
                  _selectedDay = selected;
                  _focusedDay = focused;
                });
              },
              onPageChanged: (focused) {
                _focusedDay = focused;
                _fetchSchedules();
              },
              calendarStyle: const CalendarStyle(
                markerDecoration: BoxDecoration(
                  color: Colors.orange,
                  shape: BoxShape.circle,
                ),
                todayDecoration: BoxDecoration(
                  color: Colors.blue,
                  shape: BoxShape.circle,
                ),
                selectedDecoration: BoxDecoration(
                  color: Colors.orange,
                  shape: BoxShape.circle,
                ),
              ),
              headerStyle: const HeaderStyle(
                formatButtonVisible: false,
                titleCentered: true,
              ),
            ),
            const Divider(thickness: 1),
            const Padding(
              padding: EdgeInsets.all(8.0),
              child: Text(
                "Jadwal Masak Hari Ini:",
                style: TextStyle(
                  fontWeight: FontWeight.bold,
                  color: Colors.grey,
                ),
              ),
            ),

            // --- LIST JADWAL HARI INI ---
            // Kita perlu memberikan batasan tinggi untuk ListView ini karena parent-nya SingleChildScrollView.
            // Gunakan `IntrinsicHeight` atau `ConstrainedBox` untuk menghindari overflow.
            ConstrainedBox(
              constraints: BoxConstraints(
                maxHeight:
                    MediaQuery.of(context).size.height *
                    0.33, // Batas tinggi agar tidak terlalu panjang
              ),
              child: _isLoading
                  ? const Center(child: CircularProgressIndicator())
                  : _buildDayList(),
            ),

            const SizedBox(height: 20),
            const Divider(thickness: 1),

            // [TOMBOL BIASA DI BAWAH KONTEN]
            Padding(
              padding: const EdgeInsets.all(16.0),
              child: SizedBox(
                width: double.infinity,
                child: ElevatedButton.icon(
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.blue[800],
                    foregroundColor: Colors.white,
                    padding: const EdgeInsets.symmetric(vertical: 15),
                  ),
                  label: const Text(
                    "KALKULASI JADWAL OTOMATIS",
                    style: TextStyle(fontWeight: FontWeight.bold),
                  ),
                  icon: const Icon(Icons.auto_awesome),
                  onPressed: () => _showAutoGenerateDialog(),
                ),
              ),
            ),
            const SizedBox(height: 5),
          ],
        ),
      ),
    );
  }

  Widget _buildDayList() {
    final events = _getSchedulesForDay(_selectedDay!);
    if (events.isEmpty)
      return const Center(child: Text("Tidak ada jadwal masak."));

    return ListView.builder(
      itemCount: events.length,
      itemBuilder: (context, index) {
        final schedule = events[index];

        // Check if the related route is already ACTIVE/COMPLETED to prevent accidental deletion!
        // NOTE: For now, we assume deleting the schedule is allowed by the admin, but a safer check
        // would involve querying the associated route status first!
        final isDeletable =
            true; // Simplified for now. Should check related route status.

        return Card(
          margin: const EdgeInsets.symmetric(horizontal: 16, vertical: 6),
          child: ListTile(
            leading: CircleAvatar(
              backgroundColor: Colors.orange[100],
              child: const Icon(Icons.restaurant, color: Colors.orange),
            ),
            title: Text(
              schedule.menuName,
              style: const TextStyle(fontWeight: FontWeight.bold),
            ),
            subtitle: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text("Target: ${schedule.totalPortions} Porsi"),
                Text(
                  "Masak: ${schedule.startCookingTime?.substring(0, 5)} -> Selesai: ${schedule.targetFinishTime?.substring(0, 5)}",
                  style: const TextStyle(
                    color: Colors.red,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                if (schedule.notes != null)
                  Text(
                    schedule.notes!,
                    style: const TextStyle(
                      fontStyle: FontStyle.italic,
                      fontSize: 12,
                    ),
                  ),
              ],
            ),
            // REPLACING POPUP MENU WITH DIRECT ACTION BUTTONS (Edit and Delete)
            trailing: Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                // EDIT Button
                IconButton(
                  icon: const Icon(Icons.edit, color: Colors.blue),
                  onPressed: () => _showScheduleDialog(
                    scheduleToEdit: schedule,
                  ), // Mode Edit
                ),
                // DELETE Button
                if (isDeletable) // Show delete button if allowed
                  IconButton(
                    icon: const Icon(Icons.delete, color: Colors.red),
                    onPressed: () => _confirmDelete(schedule.id),
                  ),
              ],
            ),
            // NOTE: If you want to keep the PopupMenuButton approach, use the one below.
            /*
          trailing: PopupMenuButton(
            onSelected: (value) {
              if (value == 'edit') _showScheduleDialog(scheduleToEdit: schedule);
              if (value == 'delete') _confirmDelete(schedule.id);
            },
            itemBuilder: (context) => [
              const PopupMenuItem(value: 'edit', child: Text("Edit")),
              const PopupMenuItem(value: 'delete', child: Text("Hapus", style: TextStyle(color: Colors.red))),
            ],
          ),
          */
          ),
        );
      },
    );
  }
}
